{
 "title": "Elixir Validator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "status_active" }
   ]
  },
  {
   "title": "Validator Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 5, "y": 0 },
   "targets": [
    { "expr": "status_active" }
   ]
  },
  {
   "title": "Started Date",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "protocol_service_started_timestamp_ms / 1000000"
    }
   ]
  },
  {
   "title": "Service Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "protocol_service_runtime_duration_ms_total"
    }
   ]
  },
  {
   "title": "Service Configuration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "protocol_service_config_data_info{ENV!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Configuration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "protocol_service_config_data_info{STRATEGY_EXECUTOR_DISPLAY_NAME!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Configuration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "protocol_service_config_data_info{STRATEGY_EXECUTOR_APP_VERSION!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication Connected Timestamp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authentication_connected_timestamp_ms / 1000000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Authentication Connected Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "authentication_connected_duration"
    }
   ]
  },
  {
   "title": "Last Signature Generation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signature_generated_timestamp_ms / 1000000"
    }
   ]
  },
  {
   "title": "Signature Generated Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 15 },
   "targets": [
    { "expr": "signature_generated_duration" }
   ]
  },
  {
   "title": "Authentication Authorized Timestamp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "authentication_authorized_timestamp_ms / 1000000"
    }
   ]
  },
  {
   "title": "Authentication Authorized Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "authentication_authorized_duration"
    }
   ]
  }
 ]
}